name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: ./scripts/feeds update -a
      run: ./scripts/feeds update -a

    - name: ./scripts/feeds install -a
      run: ./scripts/feeds install -a

    - name: make
      run: make
